name: Otto's Blog
description: Blogging about dev stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://andrelotto.github.io'
google_analytics: 'UA-59733095-6'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://andrelotto.github.io/'
author:         'Andr√© Luis Otto'
